
import type { Asset, NewsArticle } from '@/types';
import { 
  Apple, Briefcase, Search, Cpu, ShoppingCart, Store, Landmark, CreditCard, 
  ShoppingBag, HeartPulse, Home, GlassWater, Activity, Cloud, Network, 
  Laptop, Utensils, Fuel, Users, Car, Castle, Pill, Phone, Tractor, Plane, Palette, 
  Shirt, Shield, PaintBucket
} from 'lucide-react';

export const placeholderAssets: Asset[] = [
  // Stocks
  { 
    id: 'aapl', 
    name: 'Apple Inc.', 
    symbol: 'AAPL', 
    type: 'stock', 
    price: 170.50, 
    change24h: 1.25, 
    marketCap: 2.8e12, 
    volume24h: 50e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/apple--big.svg',
    dataAiHint: 'apple logo',
    icon: Apple,
    peRatio: 28.5,
    epsDilutedTTM: 6.00,
    epsDilutedGrowthTTMYoY: 8.5,
    dividendYieldTTM: 0.55,
    sector: 'Technology',
    relativeVolume: 1.1,
  },
  { 
    id: 'msft', 
    name: 'Microsoft Corp.', 
    symbol: 'MSFT', 
    type: 'stock', 
    price: 420.75, 
    change24h: -0.15, 
    marketCap: 3.1e12, 
    volume24h: 22e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'microsoft logo',
    icon: Briefcase,
    peRatio: 35.2,
    epsDilutedTTM: 11.50,
    epsDilutedGrowthTTMYoY: 12.3,
    dividendYieldTTM: 0.80,
    sector: 'Technology',
    relativeVolume: 0.9,
  },
  { 
    id: 'googl', 
    name: 'Alphabet Inc.', 
    symbol: 'GOOGL', 
    type: 'stock', 
    price: 175.20, 
    change24h: 0.90, 
    marketCap: 2.1e12, 
    volume24h: 18e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'google logo',
    icon: Search,
    peRatio: 25.8,
    epsDilutedTTM: 6.80,
    epsDilutedGrowthTTMYoY: 15.1,
    dividendYieldTTM: 0.00, // Google doesn't typically pay dividends
    sector: 'Communication Services',
    relativeVolume: 1.0,
  },
  { 
    id: 'nvda', 
    name: 'Nvidia Corp.', 
    symbol: 'NVDA', 
    type: 'stock', 
    price: 950.00, 
    change24h: 2.50, 
    marketCap: 2.3e12, 
    volume24h: 45e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/nvidia--big.svg',
    dataAiHint: 'nvidia logo',
    icon: Cpu,
    peRatio: 75.0,
    epsDilutedTTM: 12.50,
    epsDilutedGrowthTTMYoY: 200.0, // High growth example
    dividendYieldTTM: 0.02,
    sector: 'Technology',
    relativeVolume: 1.5,
  },
  { 
    id: 'amzn', 
    name: 'Amazon.com, Inc.', 
    symbol: 'AMZN', 
    type: 'stock', 
    price: 185.60, 
    change24h: 0.75, 
    marketCap: 1.9e12, 
    volume24h: 35e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/amazon--big.svg',
    dataAiHint: 'amazon logo',
    icon: ShoppingCart,
    peRatio: 50.5,
    epsDilutedTTM: 3.70,
    epsDilutedGrowthTTMYoY: 25.0,
    dividendYieldTTM: 0.00,
    sector: 'Consumer Discretionary',
    relativeVolume: 1.2,
  },
  { 
    id: 'wmt', 
    name: 'Walmart Inc.', 
    symbol: 'WMT', 
    type: 'stock', 
    price: 60.30, 
    change24h: -0.40, 
    marketCap: 480e9, 
    volume24h: 20e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/walmart--big.svg',
    dataAiHint: 'walmart logo',
    icon: Store,
    peRatio: 25.1,
    epsDilutedTTM: 2.40,
    epsDilutedGrowthTTMYoY: 5.2,
    dividendYieldTTM: 1.50,
    sector: 'Consumer Staples',
    relativeVolume: 0.8,
  },
  { 
    id: 'jpm', 
    name: 'JPMorgan Chase & Co.', 
    symbol: 'JPM', 
    type: 'stock', 
    price: 200.10, 
    change24h: 0.55, 
    marketCap: 570e9, 
    volume24h: 12e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/jpmorgan--big.svg',
    dataAiHint: 'jpmorgan logo',
    icon: Landmark,
    peRatio: 12.5,
    epsDilutedTTM: 16.00,
    epsDilutedGrowthTTMYoY: 10.5,
    dividendYieldTTM: 2.20,
    sector: 'Financials',
    relativeVolume: 0.95,
  },
  { 
    id: 'v', 
    name: 'Visa Inc.', 
    symbol: 'V', 
    type: 'stock', 
    price: 280.00, 
    change24h: 0.30, 
    marketCap: 560e9, 
    volume24h: 8e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/visa--big.svg',
    dataAiHint: 'visa logo',
    icon: CreditCard,
    peRatio: 30.0,
    epsDilutedTTM: 9.30,
    epsDilutedGrowthTTMYoY: 11.8,
    dividendYieldTTM: 0.70,
    sector: 'Information Technology', // Often classified here due to tech platform
    relativeVolume: 1.0,
  },
  { 
    id: 'pg', 
    name: 'Procter & Gamble Co.', 
    symbol: 'PG', 
    type: 'stock', 
    price: 165.90, 
    change24h: -0.10, 
    marketCap: 390e9, 
    volume24h: 7e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/procter-gamble--big.svg',
    dataAiHint: 'procter gamble',
    icon: ShoppingBag,
    peRatio: 26.3,
    epsDilutedTTM: 6.30,
    epsDilutedGrowthTTMYoY: 4.5,
    dividendYieldTTM: 2.40,
    sector: 'Consumer Staples',
    relativeVolume: 0.7,
  },
  { 
    id: 'jnj', 
    name: 'Johnson & Johnson', 
    symbol: 'JNJ', 
    type: 'stock', 
    price: 150.25, 
    change24h: 0.20, 
    marketCap: 370e9, 
    volume24h: 9e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/johnson-johnson--big.svg',
    dataAiHint: 'johnson johnson',
    icon: HeartPulse,
    peRatio: 22.0,
    epsDilutedTTM: 6.80,
    epsDilutedGrowthTTMYoY: 3.2,
    dividendYieldTTM: 2.90,
    sector: 'Health Care',
    relativeVolume: 0.85,
  },
  { 
    id: 'hd', 
    name: 'Home Depot, Inc.', 
    symbol: 'HD', 
    type: 'stock', 
    price: 340.50, 
    change24h: 0.80, 
    marketCap: 350e9, 
    volume24h: 5e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/home-depot--big.svg',
    dataAiHint: 'home depot',
    icon: Home,
    peRatio: 23.5,
    epsDilutedTTM: 14.50,
    epsDilutedGrowthTTMYoY: 6.1,
    dividendYieldTTM: 2.10,
    sector: 'Consumer Discretionary',
    relativeVolume: 0.9,
  },
  { 
    id: 'ko', 
    name: 'The Coca-Cola Company', 
    symbol: 'KO', 
    type: 'stock', 
    price: 63.70, 
    change24h: 0.05, 
    marketCap: 270e9, 
    volume24h: 10e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/coca-cola--big.svg',
    dataAiHint: 'coca cola',
    icon: GlassWater,
    peRatio: 25.0,
    epsDilutedTTM: 2.55,
    epsDilutedGrowthTTMYoY: 3.0,
    dividendYieldTTM: 3.00,
    sector: 'Consumer Staples',
    relativeVolume: 1.0,
  },
  { 
    id: 'unh', 
    name: 'UnitedHealth Group Inc.', 
    symbol: 'UNH', 
    type: 'stock', 
    price: 500.00, 
    change24h: -0.60, 
    marketCap: 460e9, 
    volume24h: 4e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/unitedhealth--big.svg',
    dataAiHint: 'unitedhealth logo',
    icon: Activity,
    peRatio: 20.5,
    epsDilutedTTM: 24.40,
    epsDilutedGrowthTTMYoY: 12.0,
    dividendYieldTTM: 1.60,
    sector: 'Health Care',
    relativeVolume: 0.75,
  },
  { 
    id: 'crm', 
    name: 'Salesforce, Inc.', 
    symbol: 'CRM', 
    type: 'stock', 
    price: 270.80, 
    change24h: 1.10, 
    marketCap: 260e9, 
    volume24h: 6e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/salesforce--big.svg',
    dataAiHint: 'salesforce logo',
    icon: Cloud,
    peRatio: 60.0, // Growth stocks often have high P/E
    epsDilutedTTM: 4.50,
    epsDilutedGrowthTTMYoY: 30.0,
    dividendYieldTTM: 0.00,
    sector: 'Technology',
    relativeVolume: 1.3,
  },
  { 
    id: 'csco', 
    name: 'Cisco Systems, Inc.', 
    symbol: 'CSCO', 
    type: 'stock', 
    price: 48.50, 
    change24h: 0.45, 
    marketCap: 200e9, 
    volume24h: 15e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/cisco--big.svg',
    dataAiHint: 'cisco logo',
    icon: Network,
    peRatio: 15.2,
    epsDilutedTTM: 3.20,
    epsDilutedGrowthTTMYoY: 5.5,
    dividendYieldTTM: 3.30,
    sector: 'Technology',
    relativeVolume: 1.1,
  },
  { 
    id: 'ibm', 
    name: 'International Business Machines Corp.', 
    symbol: 'IBM', 
    type: 'stock', 
    price: 170.00, 
    change24h: -0.25, 
    marketCap: 155e9, 
    volume24h: 5e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/ibm--big.svg',
    dataAiHint: 'ibm logo',
    icon: Laptop,
    peRatio: 18.0,
    epsDilutedTTM: 9.40,
    epsDilutedGrowthTTMYoY: 2.5,
    dividendYieldTTM: 3.90,
    sector: 'Technology',
    relativeVolume: 0.8,
  },
  { 
    id: 'mcd', 
    name: "McDonald's Corp.", 
    symbol: 'MCD', 
    type: 'stock', 
    price: 260.40, 
    change24h: 0.10, 
    marketCap: 190e9, 
    volume24h: 3e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/mcdonalds--big.svg',
    dataAiHint: 'mcdonalds logo',
    icon: Utensils,
    peRatio: 24.0,
    epsDilutedTTM: 10.80,
    epsDilutedGrowthTTMYoY: 8.0,
    dividendYieldTTM: 2.50,
    sector: 'Consumer Discretionary',
    relativeVolume: 0.9,
  },
  { 
    id: 'cvx', 
    name: 'Chevron Corp.', 
    symbol: 'CVX', 
    type: 'stock', 
    price: 160.90, 
    change24h: 1.30, 
    marketCap: 300e9, 
    volume24h: 7e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/chevron--big.svg',
    dataAiHint: 'chevron logo',
    icon: Fuel,
    peRatio: 11.5,
    epsDilutedTTM: 14.00,
    epsDilutedGrowthTTMYoY: -5.0, // Energy sector can have fluctuations
    dividendYieldTTM: 3.80,
    sector: 'Energy',
    relativeVolume: 1.05,
  },
  { 
    id: 'meta', 
    name: 'Meta Platforms, Inc.', 
    symbol: 'META', 
    type: 'stock', 
    price: 480.10, 
    change24h: -0.70, 
    marketCap: 1.2e12, 
    volume24h: 25e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'meta logo',
    icon: Users,
    peRatio: 30.0,
    epsDilutedTTM: 16.00,
    epsDilutedGrowthTTMYoY: 70.0, // Example of rebound/growth
    dividendYieldTTM: 0.40, // Meta recently started paying dividends
    sector: 'Communication Services',
    relativeVolume: 1.4,
  },
  { 
    id: 'tsla', 
    name: 'Tesla, Inc.', 
    symbol: 'TSLA', 
    type: 'stock', 
    price: 175.30, 
    change24h: 3.50, 
    marketCap: 560e9, 
    volume24h: 60e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'tesla logo',
    icon: Car,
    peRatio: 40.0, // High P/E typical for Tesla
    epsDilutedTTM: 4.30,
    epsDilutedGrowthTTMYoY: -10.0, // Example of recent slowdown
    dividendYieldTTM: 0.00,
    sector: 'Consumer Discretionary',
    relativeVolume: 2.0,
  },
  { 
    id: 'axp', 
    name: 'American Express Company', 
    symbol: 'AXP', 
    type: 'stock', 
    price: 230.70, 
    change24h: 0.85, 
    marketCap: 170e9, 
    volume24h: 3.5e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'american express',
    icon: CreditCard,
    peRatio: 19.5,
    epsDilutedTTM: 11.80,
    epsDilutedGrowthTTMYoY: 14.2,
    dividendYieldTTM: 1.10,
    sector: 'Financials',
    relativeVolume: 0.9,
  },
  { 
    id: 'dis', 
    name: 'The Walt Disney Company', 
    symbol: 'DIS', 
    type: 'stock', 
    price: 105.20, 
    change24h: -0.50, 
    marketCap: 190e9, 
    volume24h: 9e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'disney logo',
    icon: Castle,
    peRatio: 60.0, // Can be high due to streaming investments/turnaround
    epsDilutedTTM: 1.75,
    epsDilutedGrowthTTMYoY: 5.0,
    dividendYieldTTM: 0.30, // Disney reinstated a small dividend
    sector: 'Communication Services',
    relativeVolume: 1.1,
  },
  { 
    id: 'gs', 
    name: 'The Goldman Sachs Group, Inc.', 
    symbol: 'GS', 
    type: 'stock', 
    price: 450.90, 
    change24h: 1.15, 
    marketCap: 150e9, 
    volume24h: 2.5e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'goldman sachs',
    icon: Landmark,
    peRatio: 17.8,
    epsDilutedTTM: 25.30,
    epsDilutedGrowthTTMYoY: -20.0, // Example of earnings dip
    dividendYieldTTM: 2.40,
    sector: 'Financials',
    relativeVolume: 0.8,
  },
  { 
    id: 'mrk', 
    name: 'Merck & Co., Inc.', 
    symbol: 'MRK', 
    type: 'stock', 
    price: 130.60, 
    change24h: 0.25, 
    marketCap: 330e9, 
    volume24h: 6e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'merck logo',
    icon: Pill,
    peRatio: 70.0, // Can be high with blockbuster drugs / pipeline
    epsDilutedTTM: 1.85, // Placeholder
    epsDilutedGrowthTTMYoY: 10.0,
    dividendYieldTTM: 2.30,
    sector: 'Health Care',
    relativeVolume: 0.9,
  },
  { 
    id: 'vz', 
    name: 'Verizon Communications Inc.', 
    symbol: 'VZ', 
    type: 'stock', 
    price: 40.10, 
    change24h: -0.15, 
    marketCap: 170e9, 
    volume24h: 18e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'verizon logo',
    icon: Phone,
    peRatio: 8.5, // Telcos often have lower P/E
    epsDilutedTTM: 4.70,
    epsDilutedGrowthTTMYoY: 1.0,
    dividendYieldTTM: 6.60, // High dividend yield typical for VZ
    sector: 'Communication Services',
    relativeVolume: 1.2,
  },
  { 
    id: 'cat', 
    name: 'Caterpillar Inc.', 
    symbol: 'CAT', 
    type: 'stock', 
    price: 330.40, 
    change24h: 1.80, 
    marketCap: 170e9, 
    volume24h: 2e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'caterpillar logo',
    icon: Tractor,
    peRatio: 15.0,
    epsDilutedTTM: 22.00,
    epsDilutedGrowthTTMYoY: 25.0,
    dividendYieldTTM: 1.60,
    sector: 'Industrials',
    relativeVolume: 1.0,
  },
  { 
    id: 'ba', 
    name: 'The Boeing Company', 
    symbol: 'BA', 
    type: 'stock', 
    price: 180.00, 
    change24h: -1.20, 
    marketCap: 110e9, 
    volume24h: 7e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'boeing logo',
    icon: Plane,
    peRatio: -25.0, // Negative P/E if losses
    epsDilutedTTM: -7.20, // Negative EPS
    epsDilutedGrowthTTMYoY: 15.0, // Growth from a low/negative base
    dividendYieldTTM: 0.00, // Boeing suspended dividends
    sector: 'Industrials',
    relativeVolume: 1.3,
  },
  { 
    id: 'nke', 
    name: 'NIKE, Inc.', 
    symbol: 'NKE', 
    type: 'stock', 
    price: 95.50, 
    change24h: 0.60, 
    marketCap: 145e9, 
    volume24h: 8e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'nike logo',
    icon: Shirt,
    peRatio: 28.0,
    epsDilutedTTM: 3.40,
    epsDilutedGrowthTTMYoY: 2.0,
    dividendYieldTTM: 1.50,
    sector: 'Consumer Discretionary',
    relativeVolume: 0.95,
  },
  { 
    id: 'intc', 
    name: 'Intel Corporation', 
    symbol: 'INTC', 
    type: 'stock', 
    price: 30.80, 
    change24h: -0.20, 
    marketCap: 130e9, 
    volume24h: 30e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'intel logo',
    icon: Cpu,
    peRatio: 30.0, // Can vary wildly with restructuring
    epsDilutedTTM: 1.00,
    epsDilutedGrowthTTMYoY: -50.0, // Example of earnings drop
    dividendYieldTTM: 1.80, // Intel cut its dividend
    sector: 'Technology',
    relativeVolume: 1.5,
  },
  { 
    id: 'mmm', 
    name: '3M Company', 
    symbol: 'MMM', 
    type: 'stock', 
    price: 100.20, 
    change24h: 0.15, 
    marketCap: 55e9, 
    volume24h: 3e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: '3m logo',
    icon: Palette,
    peRatio: 10.0, // Lower due to legal issues/restructuring
    epsDilutedTTM: 10.00, // Placeholder
    epsDilutedGrowthTTMYoY: -15.0,
    dividendYieldTTM: 5.90, // High yield, but dividend sustainability concerns
    sector: 'Industrials',
    relativeVolume: 0.7,
  },
  { 
    id: 'dow', 
    name: 'Dow Inc.', 
    symbol: 'DOW', 
    type: 'stock', 
    price: 55.70, 
    change24h: 0.90, 
    marketCap: 38e9, 
    volume24h: 4e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'dow chemical',
    icon: PaintBucket,
    peRatio: 20.0, // Cyclical chemical company
    epsDilutedTTM: 2.80,
    epsDilutedGrowthTTMYoY: -25.0,
    dividendYieldTTM: 5.00,
    sector: 'Materials',
    relativeVolume: 0.85,
  },
  { 
    id: 'trv', 
    name: 'The Travelers Companies, Inc.', 
    symbol: 'TRV', 
    type: 'stock', 
    price: 210.00, 
    change24h: 0.40, 
    marketCap: 48e9, 
    volume24h: 1.5e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'travelers logo',
    icon: Shield,
    peRatio: 14.0,
    epsDilutedTTM: 15.00,
    epsDilutedGrowthTTMYoY: 10.0,
    dividendYieldTTM: 2.00,
    sector: 'Financials',
    relativeVolume: 0.6,
  },
  // Cryptocurrencies
  { 
    id: 'bitcoin', 
    name: 'Bitcoin', 
    symbol: 'BTC', 
    type: 'crypto', 
    price: 65000.00, 
    change24h: 1.50, 
    marketCap: 1.28e12, 
    volume24h: 25e9, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCBTC--big.svg',
    dataAiHint: 'bitcoin crypto',
    icon: 'B',
    circulatingSupply: "19.7M BTC",
    allTimeHigh: "$69,044.77",
  },
  // Stablecoins
  { 
    id: 'tether', 
    name: 'Tether', 
    symbol: 'USDT', 
    type: 'crypto', 
    price: 1.00, 
    change24h: 0.01, 
    marketCap: 112e9, 
    volume24h: 45e9, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCUSDT--big.svg',
    dataAiHint: 'tether crypto',
    icon: 'T',
    circulatingSupply: "112B USDT",
    allTimeHigh: "$1.02",
  },
  { 
    id: 'usd-coin', 
    name: 'USD Coin', 
    symbol: 'USDC', 
    type: 'crypto', 
    price: 1.00, 
    change24h: -0.01, 
    marketCap: 34e9, 
    volume24h: 5.5e9, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCUSDC--big.svg',
    dataAiHint: 'usdc crypto',
    icon: 'U',
    circulatingSupply: "34B USDC",
    allTimeHigh: "$1.01",
  },
  { 
    id: 'dai', 
    name: 'Dai', 
    symbol: 'DAI', 
    type: 'crypto', 
    price: 1.00, 
    change24h: 0.02, 
    marketCap: 5e9, 
    volume24h: 100e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCDAI--big.svg',
    dataAiHint: 'dai crypto',
    icon: 'D',
    circulatingSupply: "5B DAI",
    allTimeHigh: "$1.01",
  },
  { 
    id: 'trueusd', 
    name: 'TrueUSD', 
    symbol: 'TUSD', 
    type: 'crypto', 
    price: 1.00, 
    change24h: 0.00, 
    marketCap: 500e6, 
    volume24h: 30e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCTUSD--big.svg',
    dataAiHint: 'trueusd crypto',
    icon: 'T',
    circulatingSupply: "500M TUSD",
    allTimeHigh: "$1.01",
  },
  { 
    id: 'pax-dollar', 
    name: 'Pax Dollar', 
    symbol: 'USDP', 
    type: 'crypto', 
    price: 1.00, 
    change24h: 0.01, 
    marketCap: 150e6, 
    volume24h: 5e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCUSDP--big.svg',
    dataAiHint: 'pax dollar crypto',
    icon: 'P',
    circulatingSupply: "150M USDP",
    allTimeHigh: "$1.01",
  },
  // Layer 1
  { 
    id: 'ethereum', 
    name: 'Ethereum', 
    symbol: 'ETH', 
    type: 'crypto', 
    price: 3550.20, 
    change24h: 1.75, 
    marketCap: 425e9, 
    volume24h: 14e9, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCETH--big.svg',
    dataAiHint: 'ethereum crypto',
    icon: 'E',
    circulatingSupply: "120M ETH",
    allTimeHigh: "$4,891.70",
  },
  { 
    id: 'solana', 
    name: 'Solana', 
    symbol: 'SOL', 
    type: 'crypto', 
    price: 148.70, 
    change24h: 4.90, 
    marketCap: 68e9, 
    volume24h: 2.1e9, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCSOL--big.svg',
    dataAiHint: 'solana crypto',
    icon: 'S',
    circulatingSupply: "460M SOL",
    allTimeHigh: "$260.06",
  },
  { 
    id: 'cardano', 
    name: 'Cardano', 
    symbol: 'ADA', 
    type: 'crypto', 
    price: 0.44, 
    change24h: 2.80, 
    marketCap: 15.5e9, 
    volume24h: 350e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCADA--big.svg',
    dataAiHint: 'cardano crypto',
    icon: 'A',
    circulatingSupply: "35B ADA",
    allTimeHigh: "$3.10",
  },
  { 
    id: 'avalanche', 
    name: 'Avalanche', 
    symbol: 'AVAX', 
    type: 'crypto', 
    price: 34.20, 
    change24h: 3.55, 
    marketCap: 13.5e9, 
    volume24h: 450e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCAVAX--big.svg',
    dataAiHint: 'avalanche crypto',
    icon: 'A',
    circulatingSupply: "390M AVAX",
    allTimeHigh: "$146.22",
  },
  { 
    id: 'polkadot', 
    name: 'Polkadot', 
    symbol: 'DOT', 
    type: 'crypto', 
    price: 7.20, 
    change24h: 1.50, 
    marketCap: 10e9, 
    volume24h: 200e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCDOT--big.svg',
    dataAiHint: 'polkadot crypto',
    icon: 'P',
    circulatingSupply: "1.4B DOT",
    allTimeHigh: "$55.00",
  },
  { 
    id: 'near-protocol', 
    name: 'NEAR Protocol', 
    symbol: 'NEAR', 
    type: 'crypto', 
    price: 6.50, 
    change24h: 5.10, 
    marketCap: 7e9, 
    volume24h: 300e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCNEAR--big.svg',
    dataAiHint: 'near protocol crypto',
    icon: 'N',
    circulatingSupply: "1.1B NEAR",
    allTimeHigh: "$20.44",
  },
  { 
    id: 'algorand', 
    name: 'Algorand', 
    symbol: 'ALGO', 
    type: 'crypto', 
    price: 0.18, 
    change24h: 0.90, 
    marketCap: 1.5e9, 
    volume24h: 50e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCALGO--big.svg',
    dataAiHint: 'algorand crypto',
    icon: 'A',
    circulatingSupply: "8.1B ALGO",
    allTimeHigh: "$3.28",
  },
  // DeFi
  { 
    id: 'uniswap', 
    name: 'Uniswap', 
    symbol: 'UNI', 
    type: 'crypto', 
    price: 10.50, 
    change24h: 3.20, 
    marketCap: 7.8e9, 
    volume24h: 150e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCUNI--big.svg',
    dataAiHint: 'uniswap crypto',
    icon: 'U',
    circulatingSupply: "750M UNI",
    allTimeHigh: "$44.97",
  },
  { 
    id: 'aave', 
    name: 'Aave', 
    symbol: 'AAVE', 
    type: 'crypto', 
    price: 90.20, 
    change24h: 2.10, 
    marketCap: 1.3e9, 
    volume24h: 60e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCAAVE--big.svg',
    dataAiHint: 'aave crypto',
    icon: 'A',
    circulatingSupply: "14.8M AAVE",
    allTimeHigh: "$666.86",
  },
  { 
    id: 'compound', 
    name: 'Compound', 
    symbol: 'COMP', 
    type: 'crypto', 
    price: 55.80, 
    change24h: -0.50, 
    marketCap: 450e6, 
    volume24h: 25e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCCOMP--big.svg',
    dataAiHint: 'compound crypto',
    icon: 'C',
    circulatingSupply: "8M COMP",
    allTimeHigh: "$911.20",
  },
  { 
    id: 'maker', 
    name: 'Maker', 
    symbol: 'MKR', 
    type: 'crypto', 
    price: 2400.00, 
    change24h: 1.80, 
    marketCap: 2.2e9, 
    volume24h: 70e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCMKR--big.svg',
    dataAiHint: 'maker crypto',
    icon: 'M',
    circulatingSupply: "920K MKR",
    allTimeHigh: "$6,339.02",
  },
  { 
    id: 'curve-dao', 
    name: 'Curve DAO', 
    symbol: 'CRV', 
    type: 'crypto', 
    price: 0.45, 
    change24h: 4.50, 
    marketCap: 550e6, 
    volume24h: 40e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCCRV--big.svg',
    dataAiHint: 'curve dao crypto',
    icon: 'C',
    circulatingSupply: "1.2B CRV",
    allTimeHigh: "$60.50", // Initial high price
  },
  { 
    id: 'sushiswap', 
    name: 'SushiSwap', 
    symbol: 'SUSHI', 
    type: 'crypto', 
    price: 1.20, 
    change24h: 2.70, 
    marketCap: 300e6, 
    volume24h: 35e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCSUSHI--big.svg',
    dataAiHint: 'sushiswap crypto',
    icon: 'S',
    circulatingSupply: "250M SUSHI",
    allTimeHigh: "$23.38",
  },
  // Meme Coins
  { 
    id: 'dogecoin', 
    name: 'Dogecoin', 
    symbol: 'DOGE', 
    type: 'crypto', 
    price: 0.145, 
    change24h: 8.75, 
    marketCap: 20e9, 
    volume24h: 800e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCDOGE--big.svg',
    dataAiHint: 'dogecoin crypto',
    icon: 'D',
    circulatingSupply: "144B DOGE",
    allTimeHigh: "$0.7376",
  },
  { 
    id: 'shiba-inu', 
    name: 'Shiba Inu', 
    symbol: 'SHIB', 
    type: 'crypto', 
    price: 0.000025, 
    change24h: 6.20, 
    marketCap: 14.5e9, 
    volume24h: 600e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCSHIB--big.svg',
    dataAiHint: 'shiba inu crypto',
    icon: 'S',
    circulatingSupply: "589T SHIB",
    allTimeHigh: "$0.00008845",
  },
  { 
    id: 'floki', 
    name: 'Floki', 
    symbol: 'FLOKI', 
    type: 'crypto', 
    price: 0.00018, 
    change24h: 10.50, 
    marketCap: 1.7e9, 
    volume24h: 150e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCFLOKI--big.svg',
    dataAiHint: 'floki crypto',
    icon: 'F',
    circulatingSupply: "9.7T FLOKI",
    allTimeHigh: "$0.0003437",
  },
  { 
    id: 'pepe', 
    name: 'Pepe', 
    symbol: 'PEPE', 
    type: 'crypto', 
    price: 0.000012, 
    change24h: 15.00, 
    marketCap: 5e9, 
    volume24h: 700e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCPEPE--big.svg',
    dataAiHint: 'pepe crypto',
    icon: 'P',
    circulatingSupply: "420T PEPE",
    allTimeHigh: "$0.00001717",
  },
  { 
    id: 'baby-doge-coin', 
    name: 'Baby Doge Coin', 
    symbol: 'BabyDoge', 
    type: 'crypto', 
    price: 0.0000000015, 
    change24h: 5.80, 
    marketCap: 250e6, 
    volume24h: 5e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'baby doge coin crypto',
    icon: 'B',
    circulatingSupply: "150Q BabyDoge", // Quadrillion
    allTimeHigh: "$0.000000006345",
  },
  // Layer 2
  { 
    id: 'polygon', 
    name: 'Polygon', 
    symbol: 'MATIC', 
    type: 'crypto', 
    price: 0.70, 
    change24h: 2.20, 
    marketCap: 6.9e9, 
    volume24h: 280e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCMATIC--big.svg',
    dataAiHint: 'polygon matic crypto',
    icon: 'M',
    circulatingSupply: "9.9B MATIC",
    allTimeHigh: "$2.92",
  },
  { 
    id: 'arbitrum', 
    name: 'Arbitrum', 
    symbol: 'ARB', 
    type: 'crypto', 
    price: 1.10, 
    change24h: 3.80, 
    marketCap: 3e9, 
    volume24h: 200e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCARB--big.svg',
    dataAiHint: 'arbitrum crypto',
    icon: 'A',
    circulatingSupply: "2.9B ARB",
    allTimeHigh: "$2.39",
  },
  { 
    id: 'optimism', 
    name: 'Optimism', 
    symbol: 'OP', 
    type: 'crypto', 
    price: 2.50, 
    change24h: 1.90, 
    marketCap: 2.6e9, 
    volume24h: 150e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCOP--big.svg',
    dataAiHint: 'optimism crypto',
    icon: 'O',
    circulatingSupply: "1.1B OP",
    allTimeHigh: "$4.84",
  },
  { 
    id: 'loopring', 
    name: 'Loopring', 
    symbol: 'LRC', 
    type: 'crypto', 
    price: 0.28, 
    change24h: -0.70, 
    marketCap: 380e6, 
    volume24h: 20e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCLRC--big.svg',
    dataAiHint: 'loopring crypto',
    icon: 'L',
    circulatingSupply: "1.3B LRC",
    allTimeHigh: "$3.83",
  },
  { 
    id: 'zksync', 
    name: 'zkSync', 
    symbol: 'ZK', 
    type: 'crypto', 
    price: 0.25, 
    change24h: 1.00, 
    marketCap: 500e6, // Placeholder
    volume24h: 10e6,  
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'zksync crypto',
    icon: 'Z',
    circulatingSupply: "2B ZK", // Placeholder
    allTimeHigh: "$0.50", // Placeholder
  },
  // Infrastructure & Oracles
  { 
    id: 'chainlink', 
    name: 'Chainlink', 
    symbol: 'LINK', 
    type: 'crypto', 
    price: 15.80, 
    change24h: 2.50, 
    marketCap: 9.3e9, 
    volume24h: 350e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCLINK--big.svg',
    dataAiHint: 'chainlink crypto',
    icon: 'L',
    circulatingSupply: "587M LINK",
    allTimeHigh: "$52.88",
  },
  { 
    id: 'cosmos', 
    name: 'Cosmos', 
    symbol: 'ATOM', 
    type: 'crypto', 
    price: 8.50, 
    change24h: 1.20, 
    marketCap: 3.3e9, 
    volume24h: 120e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCATOM--big.svg',
    dataAiHint: 'cosmos atom crypto',
    icon: 'A',
    circulatingSupply: "390M ATOM",
    allTimeHigh: "$44.70",
  },
  { 
    id: 'the-graph', 
    name: 'The Graph', 
    symbol: 'GRT', 
    type: 'crypto', 
    price: 0.30, 
    change24h: 4.10, 
    marketCap: 2.8e9, 
    volume24h: 90e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCGRT--big.svg',
    dataAiHint: 'the graph crypto',
    icon: 'G',
    circulatingSupply: "9.5B GRT",
    allTimeHigh: "$2.88",
  },
  { 
    id: 'filecoin', 
    name: 'Filecoin', 
    symbol: 'FIL', 
    type: 'crypto', 
    price: 6.00, 
    change24h: 0.80, 
    marketCap: 3.3e9, 
    volume24h: 100e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCFIL--big.svg',
    dataAiHint: 'filecoin crypto',
    icon: 'F',
    circulatingSupply: "560M FIL",
    allTimeHigh: "$237.24",
  },
  { 
    id: 'helium', 
    name: 'Helium', 
    symbol: 'HNT', 
    type: 'crypto', 
    price: 4.20, 
    change24h: -1.50, 
    marketCap: 680e6, 
    volume24h: 15e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCHNT--big.svg',
    dataAiHint: 'helium crypto',
    icon: 'H',
    circulatingSupply: "160M HNT",
    allTimeHigh: "$55.22",
  },
  // Privacy Coins
  { 
    id: 'monero', 
    name: 'Monero', 
    symbol: 'XMR', 
    type: 'crypto', 
    price: 140.50, 
    change24h: 0.50, 
    marketCap: 2.6e9, 
    volume24h: 50e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCXMR--big.svg',
    dataAiHint: 'monero crypto',
    icon: 'M',
    circulatingSupply: "18.4M XMR",
    allTimeHigh: "$542.33",
  },
  { 
    id: 'zcash', 
    name: 'Zcash', 
    symbol: 'ZEC', 
    type: 'crypto', 
    price: 25.00, 
    change24h: 1.10, 
    marketCap: 400e6, 
    volume24h: 30e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCZEC--big.svg',
    dataAiHint: 'zcash crypto',
    icon: 'Z',
    circulatingSupply: "16.3M ZEC",
    allTimeHigh: "$3,191.93", // Initial high price
  },
  { 
    id: 'secret', 
    name: 'Secret', 
    symbol: 'SCRT', 
    type: 'crypto', 
    price: 0.55, 
    change24h: 3.30, 
    marketCap: 100e6, 
    volume24h: 2e6, 
    logoUrl: 'https://s3-symbol-logo.tradingview.com/crypto/XTVCSCRT--big.svg',
    dataAiHint: 'secret crypto',
    icon: 'S',
    circulatingSupply: "190M SCRT",
    allTimeHigh: "$10.64",
  },
];

export const placeholderNews: NewsArticle[] = [
  { id: 'news1', title: 'Market Hits Record Highs Amidst Tech Rally', source: 'Finance News Today', publishedAt: new Date(Date.now() - 3600000).toISOString(), url: '#', summary: 'Major indices soared today, largely driven by strong earnings reports from leading technology companies.' },
  { id: 'news2', title: 'Interest Rate Speculation Shakes Bond Markets', source: 'Global Economic Review', publishedAt: new Date(Date.now() - 7200000).toISOString(), url: '#', summary: 'Bond yields saw increased volatility as traders reacted to comments from central bank officials.' },
  { id: 'news3', title: 'Federal Reserve Signals Potential Interest Rate Adjustments', source: 'Economic Times', publishedAt: new Date(Date.now() - 10800000).toISOString(), url: '#', summary: 'The Federal Reserve hinted at possible changes to interest rates in the coming months, depending on inflation data.' },
];

export function getAssetById(id: string): Asset | undefined {
  return placeholderAssets.find(asset => asset.id === id);
}
