import type { Asset, NewsArticle } from '@/types';
import { 
  Apple, Briefcase, Search, Cpu, ShoppingCart, Store, Landmark, CreditCard, 
  ShoppingBag, HeartPulse, Home, GlassWater, Activity, Cloud, Network, 
  Laptop, Utensils, Fuel, Users, Car, DollarSign, Castle, Pill, Phone, Tractor, Plane, Palette // Added Palette as a generic icon
} from 'lucide-react';

export const placeholderAssets: Asset[] = [
  { 
    id: 'aapl', 
    name: 'Apple Inc.', 
    symbol: 'AAPL', 
    type: 'stock', 
    price: 170.50, 
    change24h: 1.25, 
    marketCap: 2.8e12, 
    volume24h: 50e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'apple logo',
    icon: Apple 
  },
  { 
    id: 'msft', 
    name: 'Microsoft Corp.', 
    symbol: 'MSFT', 
    type: 'stock', 
    price: 420.75, 
    change24h: -0.15, 
    marketCap: 3.1e12, 
    volume24h: 22e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'microsoft logo',
    icon: Briefcase 
  },
  { 
    id: 'googl', 
    name: 'Alphabet Inc.', 
    symbol: 'GOOGL', 
    type: 'stock', 
    price: 175.20, 
    change24h: 0.90, 
    marketCap: 2.1e12, 
    volume24h: 18e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'google logo',
    icon: Search
  },
  { 
    id: 'nvda', 
    name: 'Nvidia Corp.', 
    symbol: 'NVDA', 
    type: 'stock', 
    price: 950.00, 
    change24h: 2.50, 
    marketCap: 2.3e12, 
    volume24h: 45e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'nvidia logo',
    icon: Cpu
  },
  { 
    id: 'amzn', 
    name: 'Amazon.com, Inc.', 
    symbol: 'AMZN', 
    type: 'stock', 
    price: 185.60, 
    change24h: 0.75, 
    marketCap: 1.9e12, 
    volume24h: 35e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'amazon logo',
    icon: ShoppingCart
  },
  { 
    id: 'wmt', 
    name: 'Walmart Inc.', 
    symbol: 'WMT', 
    type: 'stock', 
    price: 60.30, 
    change24h: -0.40, 
    marketCap: 480e9, 
    volume24h: 20e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'walmart logo',
    icon: Store
  },
  { 
    id: 'jpm', 
    name: 'JPMorgan Chase & Co.', 
    symbol: 'JPM', 
    type: 'stock', 
    price: 200.10, 
    change24h: 0.55, 
    marketCap: 570e9, 
    volume24h: 12e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'jpmorgan logo',
    icon: Landmark
  },
  { 
    id: 'v', 
    name: 'Visa Inc.', 
    symbol: 'V', 
    type: 'stock', 
    price: 280.00, 
    change24h: 0.30, 
    marketCap: 560e9, 
    volume24h: 8e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'visa logo',
    icon: CreditCard
  },
  { 
    id: 'pg', 
    name: 'Procter & Gamble Co.', 
    symbol: 'PG', 
    type: 'stock', 
    price: 165.90, 
    change24h: -0.10, 
    marketCap: 390e9, 
    volume24h: 7e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'procter gamble',
    icon: ShoppingBag
  },
  { 
    id: 'jnj', 
    name: 'Johnson & Johnson', 
    symbol: 'JNJ', 
    type: 'stock', 
    price: 150.25, 
    change24h: 0.20, 
    marketCap: 370e9, 
    volume24h: 9e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'johnson johnson',
    icon: HeartPulse
  },
  { 
    id: 'hd', 
    name: 'Home Depot, Inc.', 
    symbol: 'HD', 
    type: 'stock', 
    price: 340.50, 
    change24h: 0.80, 
    marketCap: 350e9, 
    volume24h: 5e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'home depot',
    icon: Home
  },
  { 
    id: 'ko', 
    name: 'The Coca-Cola Company', 
    symbol: 'KO', 
    type: 'stock', 
    price: 63.70, 
    change24h: 0.05, 
    marketCap: 270e9, 
    volume24h: 10e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'coca cola',
    icon: GlassWater
  },
  { 
    id: 'unh', 
    name: 'UnitedHealth Group Inc.', 
    symbol: 'UNH', 
    type: 'stock', 
    price: 500.00, 
    change24h: -0.60, 
    marketCap: 460e9, 
    volume24h: 4e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'unitedhealth logo',
    icon: Activity
  },
  { 
    id: 'crm', 
    name: 'Salesforce, Inc.', 
    symbol: 'CRM', 
    type: 'stock', 
    price: 270.80, 
    change24h: 1.10, 
    marketCap: 260e9, 
    volume24h: 6e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'salesforce logo',
    icon: Cloud
  },
  { 
    id: 'csco', 
    name: 'Cisco Systems, Inc.', 
    symbol: 'CSCO', 
    type: 'stock', 
    price: 48.50, 
    change24h: 0.45, 
    marketCap: 200e9, 
    volume24h: 15e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'cisco logo',
    icon: Network
  },
  { 
    id: 'ibm', 
    name: 'International Business Machines Corp.', 
    symbol: 'IBM', 
    type: 'stock', 
    price: 170.00, 
    change24h: -0.25, 
    marketCap: 155e9, 
    volume24h: 5e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'ibm logo',
    icon: Laptop
  },
  { 
    id: 'mcd', 
    name: "McDonald's Corp.", 
    symbol: 'MCD', 
    type: 'stock', 
    price: 260.40, 
    change24h: 0.10, 
    marketCap: 190e9, 
    volume24h: 3e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'mcdonalds logo',
    icon: Utensils
  },
  { 
    id: 'cvx', 
    name: 'Chevron Corp.', 
    symbol: 'CVX', 
    type: 'stock', 
    price: 160.90, 
    change24h: 1.30, 
    marketCap: 300e9, 
    volume24h: 7e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'chevron logo',
    icon: Fuel
  },
  { 
    id: 'meta', 
    name: 'Meta Platforms, Inc.', 
    symbol: 'META', 
    type: 'stock', 
    price: 480.10, 
    change24h: -0.70, 
    marketCap: 1.2e12, 
    volume24h: 25e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'meta logo',
    icon: Users
  },
  { 
    id: 'tsla', 
    name: 'Tesla, Inc.', 
    symbol: 'TSLA', 
    type: 'stock', 
    price: 175.30, 
    change24h: 3.50, 
    marketCap: 560e9, 
    volume24h: 60e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'tesla logo',
    icon: Car
  },
  { 
    id: 'axp', 
    name: 'American Express Company', 
    symbol: 'AXP', 
    type: 'stock', 
    price: 230.70, 
    change24h: 0.85, 
    marketCap: 170e9, 
    volume24h: 3.5e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'american express',
    icon: CreditCard // Reusing, appropriate
  },
  { 
    id: 'dis', 
    name: 'The Walt Disney Company', 
    symbol: 'DIS', 
    type: 'stock', 
    price: 105.20, 
    change24h: -0.50, 
    marketCap: 190e9, 
    volume24h: 9e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'disney logo',
    icon: Castle 
  },
  { 
    id: 'gs', 
    name: 'The Goldman Sachs Group, Inc.', 
    symbol: 'GS', 
    type: 'stock', 
    price: 450.90, 
    change24h: 1.15, 
    marketCap: 150e9, 
    volume24h: 2.5e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'goldman sachs',
    icon: Landmark // Reusing, appropriate
  },
  { 
    id: 'mrk', 
    name: 'Merck & Co., Inc.', 
    symbol: 'MRK', 
    type: 'stock', 
    price: 130.60, 
    change24h: 0.25, 
    marketCap: 330e9, 
    volume24h: 6e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'merck logo',
    icon: Pill
  },
  { 
    id: 'vz', 
    name: 'Verizon Communications Inc.', 
    symbol: 'VZ', 
    type: 'stock', 
    price: 40.10, 
    change24h: -0.15, 
    marketCap: 170e9, 
    volume24h: 18e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'verizon logo',
    icon: Phone
  },
  { 
    id: 'cat', 
    name: 'Caterpillar Inc.', 
    symbol: 'CAT', 
    type: 'stock', 
    price: 330.40, 
    change24h: 1.80, 
    marketCap: 170e9, 
    volume24h: 2e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'caterpillar logo',
    icon: Tractor
  },
  { 
    id: 'ba', 
    name: 'The Boeing Company', 
    symbol: 'BA', 
    type: 'stock', 
    price: 180.00, 
    change24h: -1.20, 
    marketCap: 110e9, 
    volume24h: 7e6, 
    logoUrl: 'https://placehold.co/40x40.png',
    dataAiHint: 'boeing logo',
    icon: Plane
  },
];

export const placeholderNews: NewsArticle[] = [
  { id: 'news1', title: 'Market Hits Record Highs Amidst Tech Rally', source: 'Finance News Today', publishedAt: new Date(Date.now() - 3600000).toISOString(), url: '#', summary: 'Major indices soared today, largely driven by strong earnings reports from leading technology companies.' },
  { id: 'news2', title: 'Interest Rate Speculation Shakes Bond Markets', source: 'Global Economic Review', publishedAt: new Date(Date.now() - 7200000).toISOString(), url: '#', summary: 'Bond yields saw increased volatility as traders reacted to comments from central bank officials.' },
  { id: 'news3', title: 'Federal Reserve Signals Potential Interest Rate Adjustments', source: 'Economic Times', publishedAt: new Date(Date.now() - 10800000).toISOString(), url: '#', summary: 'The Federal Reserve hinted at possible changes to interest rates in the coming months, depending on inflation data.' },
];

export function getAssetById(id: string): Asset | undefined {
  return placeholderAssets.find(asset => asset.id === id);
}

